### PR TITLE
Added support for per-file compiler flags

### PR DESCRIPTION
**Pull request by twobitlabs**
Allows you to specify one or more compiler flags to be added to each build file reference. The main reason for this is using VendorKit to include a non-ARC library in an ARC project. You can see an example of where we're doing this at https://github.com/twobitlabs/expecta

### CODE REVIEW

**Comment by keithpitt** [comment]
This is awesome. Could you expand on what the per_file_flag does in a comment in the example? Once that's done, I'll merge it in!

**Comment by burtlo** [comment]
@twobitlabs since @keithpitt merged in the changes that I made to use [xcoder](https://github.com/rayh/xcoder), this functionality should be supported.

**Comment by burtlo** [comment]
@twobitlabs it was awesome that you pointed this out to me as I did not have that functionality within Xcoder to provide support for such things.

**Comment by burtlo** [comment]
Because I changed the implementation drastically, I copied your tests and the small snippets of the code that you created and manually merged them.

**Comment by burtlo** [comment]
This feature is complete.

**Pull request closed without merging**
